# Generated by Django 5.2.5 on 2025-09-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pago_remove_pedido_metodo_pago_delete_metodopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('rechazado', 'Rechazado (tiempo expirado)'), ('pendiente', 'Pendiente de confirmar'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20),
        ),
    ]
