# Generated by Django 5.2.5 on 2025-09-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
